server:
  port: 8989
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(W5p2CjSM+dafOGhlhKaKx3hriew7tlfwYWxdHJwYMdn7Px2o1uCEzsWGEq0UgJlZ)
    schema: classpath:sql/schema.sql
    url: jdbc:mysql://localhost:3306/shorturl?socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC
    username: root
  redis:
    database: 0
    host: localhost
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        max-wait: 5000
    password: ''
    port: 6379
    timeout: 3000
swagger:
  open: true
url-shortener:
  baseurl: http://localhost:8989/s/
  strategy: hash